package jetbrains.mps.ide.depanalyzer.actions;

/*Generated by MPS */

import jetbrains.mps.plugins.tool.GeneratedTool;
import javax.swing.Icon;
import com.intellij.icons.AllIcons;
import jetbrains.mps.ide.depanalyzer.ModuleDependenciesView;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.wm.ToolWindowAnchor;
import org.jetbrains.mps.openapi.module.SModule;
import javax.swing.JComponent;

public class ModuleDependencies_Tool extends GeneratedTool {
  private static final Icon ICON = AllIcons.Toolwindows.ToolWindowModuleDependencies;
  private ModuleDependenciesView myComponent;
  public ModuleDependencies_Tool(Project project) {
    super(project, "Module Dependencies", null, ICON, ToolWindowAnchor.BOTTOM, false);
  }
  public void init(Project project) {
    super.init(project);
    ModuleDependencies_Tool.this.myComponent = new ModuleDependenciesView(ModuleDependencies_Tool.this, project);
  }
  public void dispose() {
    if (ModuleDependencies_Tool.this.myComponent != null) {
      ModuleDependencies_Tool.this.myComponent.dispose();
      ModuleDependencies_Tool.this.myComponent = null;
    }
    super.dispose();
  }
  /*package*/ void setModules(SModule module) {
    ModuleDependencies_Tool.this.myComponent.setModules(module);
  }
  public void resetAll() {
    ModuleDependencies_Tool.this.myComponent.resetAll();
  }
  public JComponent getComponent() {
    return ModuleDependencies_Tool.this.myComponent;
  }
}
