package jetbrains.mps.ide.devkit.actions;

/*Generated by MPS */

import jetbrains.mps.plugins.tool.GeneratedTool;
import javax.swing.Icon;
import jetbrains.mps.icons.MPSIcons;
import jetbrains.mps.ide.devkit.typesystem.trace.TypeSystemTracePanel;
import jetbrains.mps.editor.EditorComponentTrackService;
import jetbrains.mps.editor.EditorComponentLifecycleListener;
import jetbrains.mps.nodeEditor.EditorComponent;
import com.intellij.openapi.project.Project;
import jetbrains.mps.ide.tools.BaseTool;
import com.intellij.openapi.wm.ToolWindowAnchor;
import jetbrains.mps.ide.project.ProjectHelper;
import org.jetbrains.annotations.NotNull;
import com.intellij.openapi.util.Disposer;
import jetbrains.mps.project.MPSProject;
import org.jetbrains.mps.openapi.model.SNode;
import javax.swing.JComponent;

public class TraceTool_Tool extends GeneratedTool {
  private static final Icon ICON = MPSIcons.ToolWindows.TypeTraceView;
  private TypeSystemTracePanel myPanel;
  private EditorComponentTrackService myTrackService;
  private EditorComponentLifecycleListener myListener;
  private EditorComponent myEditorComponent;
  public TraceTool_Tool(Project project) {
    super(project, "Typesystem Trace", BaseTool.shortcutsFromNumber(5), ICON, ToolWindowAnchor.RIGHT, false);
  }
  public void init(Project project) {
    super.init(project);
    TraceTool_Tool.this.myPanel = new TypeSystemTracePanel(TraceTool_Tool.this);

    TraceTool_Tool.this.myTrackService = ProjectHelper.fromIdeaProjectOrFail(project).getComponent(EditorComponentTrackService.class);
    TraceTool_Tool.this.myListener = new EditorComponentLifecycleListener() {
      public void editorComponentDisposed(@NotNull org.jetbrains.mps.openapi.project.Project mpsProject, @NotNull jetbrains.mps.openapi.editor.EditorComponent ecomp) {
        if (ecomp == TraceTool_Tool.this.myEditorComponent) {
          TraceTool_Tool.this.myPanel.cleanUp();
          TraceTool_Tool.this.myEditorComponent = null;
        }
      }
    };
    if (TraceTool_Tool.this.myTrackService != null) {
      TraceTool_Tool.this.myTrackService.addListener(TraceTool_Tool.this.myListener);
    }
  }
  public void dispose() {
    Disposer.dispose(TraceTool_Tool.this.myPanel);
    if (TraceTool_Tool.this.myTrackService != null) {
      TraceTool_Tool.this.myTrackService.removeListener(TraceTool_Tool.this.myListener);
    }
    super.dispose();
  }
  public void buildTrace(MPSProject mpsProject, SNode node, EditorComponent editorComponent) {
    TraceTool_Tool.this.myEditorComponent = editorComponent;
    TraceTool_Tool.this.myPanel.showTraceForNode(mpsProject, node, editorComponent);
  }
  public JComponent getComponent() {
    return TraceTool_Tool.this.myPanel;
  }
}
